version: "3.8"


x-common: &commons
  mem_swappiness: 0
  deploy:
    resources:
      limits:
        memory: 600m


services:
  proxy:
    <<: *commons
    image: traefik:1.7.28-alpine
    container_name: proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    command:
      - --log.level=DEBUG
      - --log.filePath=/mnt/full.log
      - --accesslog=true
      - --accesslog.filepath=/mnt/access.log
      - --accesslog.bufferingsize=1
      - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      #- --certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.mytlschallenge.acme.email=letsencrypt@final04.com
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json

  app:
    <<: *commons
    build:
      context: .
    container_name: app
    image: app:1
    depends_on:
      - proxy
    volumes:
      - "./data:/app/data:rw"
    mem_swappiness: 0
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.app.rule=Host(`0.0.0.0`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=mytlschallenge
      - traefik.http.routers.app.tls=true
    ports:
      - "8000:8000"
    entrypoint:  uvicorn api:app --host=0.0.0.0
