version: "3.8"


x-common: &commons
  mem_swappiness: 0
  deploy:
    resources:
      limits:
        memory: 600m


services:
  proxy:
    <<: *commons
    image: traefik:v2.4.8
    container_name: pi_proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "127.0.0.1:8080:8080"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - app

  app:
    <<: *commons
    build:
      context: .
    container_name: pi_app
    image: pi_app:1
    volumes:
      - "./data:/app/data:rw"
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`pi.localhost`)
    entrypoint:  uvicorn api:app --host=0.0.0.0
    expose:
      - 8000
